version: "3"
services:
  mongodb:
    image: mongo:3.2
    volumes:
      - mongodata:/data/db

    restart: always
  creation-service:
    image: volkangurbuz/creation-service
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

volumes:
  mongodata: